# NOTE: Code comments in this file were generated by ChatGPT.

import re
import pickle
import numpy as np
import pandas as pd
import requests
import streamlit as st
import streamlit.components.v1 as components
import tensorflow as tf
from bs4 import BeautifulSoup
from urllib.parse import urlparse
from tensorflow.keras.preprocessing.sequence import pad_sequences
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from lime.lime_text import LimeTextExplainer
import nltk

# Ensure required NLTK resources are available at runtime
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")

# Paths to different tokenizers and maximum sequence length for the model input
TOKENIZER_PATH_DEFAULT = "notebooks/tokenizer.pkl"
TOKENIZER_PATH_ITER = "notebooks/tokenizer_iterative.pkl"
MAXLEN = 200

# LIME text explainer configured with the model’s class names
explainer = LimeTextExplainer(class_names=["fake", "real"])


@st.cache_resource
def load_selected_model(choice: str):
    """
    Load a model and its associated tokenizer based on the user’s version choice.
    Results are cached as a Streamlit resource.
    """
    if choice == "1.0":
        model_path = "notebooks/best_model.keras"
        tokenizer_path = TOKENIZER_PATH_DEFAULT
    elif choice == "1.1":
        model_path = "notebooks/finetuned_model.keras"
        tokenizer_path = TOKENIZER_PATH_DEFAULT
    elif choice == "1.2":
        model_path = "notebooks/v3_model.keras"
        tokenizer_path = TOKENIZER_PATH_DEFAULT
    elif choice == "2.0":
        model_path = "notebooks/curriculum_best_model.keras"
        tokenizer_path = TOKENIZER_PATH_ITER
    elif choice == "3.0":
        model_path = "notebooks/merged_model.keras"
        tokenizer_path = "notebooks/tokenizer_merged.pkl"
    else:
        return None, None

    # Clear Keras session to avoid graph accumulation when switching models
    tf.keras.backend.clear_session()

    # Load the selected model without recompiling
    model = tf.keras.models.load_model(model_path, compile=False)

    # Load the associated tokenizer from disk
    with open(tokenizer_path, "rb") as f:
        tokenizer = pickle.load(f)
    return model, tokenizer


@st.cache_data(show_spinner=False)
def fetch_article_text(url, timeout=15):
    """
    Fetch and parse article text from a URL.
    Attempts structured extraction first, then falls back to all <p> tags.
    Returns (text, metadata).
    """
    headers = {"User-Agent": "Mozilla/5.0"}
    r = requests.get(url, headers=headers, timeout=timeout)
    soup = BeautifulSoup(r.text, "html.parser")

    # Remove non-content tags that could pollute text extraction
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    # Extract page title if available
    title = ""
    if soup.title and soup.title.string:
        title = soup.title.string.strip()
    domain = urlparse(url).netloc
    mode = "none"
    paragraph_count = 0

    # Structured extraction using common article container selectors
    selectors = [
        "article",
        "main",
        "div[itemprop='articleBody']",
        "div#content",
        "div.article-body",
        "div.post-content",
        "section.article",
        "section#content",
        "div.story-body__inner",
    ]
    for sel in selectors:
        c = soup.select_one(sel)
        if c:
            ps = c.find_all("p")
            txts = [
                p.get_text(" ", strip=True)
                for p in ps
                if p.get_text(strip=True)
            ]
            if txts:
                paragraph_count = len(txts)
                mode = "structured"
                text = "\n\n".join(txts).strip()
                meta = {
                    "paragraphs": paragraph_count,
                    "title": title,
                    "domain": domain,
                    "mode": mode,
                }
                return text, meta

    # Fallback: concatenate all <p> tags if structured extraction fails
    ps = soup.find_all("p")
    txts = [p.get_text(" ", strip=True) for p in ps if p.get_text(strip=True)]
    text = "\n\n".join(txts).strip()
    paragraph_count = len(ps)
    mode = "fallback" if text else "empty"
    meta = {
        "paragraphs": paragraph_count,
        "title": title,
        "domain": domain,
        "mode": mode,
    }
    return text, meta


def process_text(text: str):
    """
    Normalize, tokenize, lemmatize, and filter the input text.
    Returns a list of unique tokens preserving first occurrence order.
    """
    # Collapse whitespace and remove non-letter characters
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Tokenize and lowercase
    tokens = word_tokenize(text.lower())

    # Lemmatize tokens
    lemma = WordNetLemmatizer()
    tokens = [lemma.lemmatize(w) for w in tokens]

    # Remove English stopwords and very short tokens
    sw = set(stopwords.words("english"))
    tokens = [w for w in tokens if w not in sw and len(w) > 3]

    # Keep only the first occurrence of each token (order-preserving uniqueness)
    uniq_idx = np.unique(tokens, return_index=True)[1]
    return np.array(tokens)[np.sort(uniq_idx)].tolist()


def predict_factory(model, tokenizer):
    """
    Build a prediction function compatible with LIME.
    Converts raw text into model-ready input and returns [fake, real] probabilities.
    """

    def predict_fn(text_list):
        # Preprocess the text list into space-joined token strings
        processed = [" ".join(process_text(t)) for t in text_list]
        # Convert text to token IDs using the tokenizer
        seq = tokenizer.texts_to_sequences(processed)
        # Pad sequences to fixed length
        padded = pad_sequences(seq, maxlen=MAXLEN)
        # Run model prediction
        p = model.predict(padded, verbose=0)
        p = np.array(p)

        # Normalize shape to (n_samples, n_classes)
        if p.ndim == 1:
            p = p.reshape(-1, 1)
        # If model outputs a single probability, treat it as 'real' and derive 'fake'
        if p.shape[1] == 1:
            real = p
            fake = 1 - real
            p = np.concatenate([fake, real], axis=1)
        return p

    return predict_fn


def build_highlighted_html(net_weights, text):
    """
    Build an HTML page with token-level background highlights reflecting net weights.
    Positive net weight → supports REAL; negative net weight → supports FAKE.
    """
    # Compute max magnitude for scaling alpha channel
    max_abs = max(abs(v) for v in net_weights.values()) if net_weights else 1

    # Split text into tokens and separators, keeping delimiters
    parts = re.split(r"(\W+)", text)
    spans = []

    for p in parts:
        if p == "":
            continue
        # If this part is purely non-word characters, keep as-is
        if re.match(r"\W+", p):
            spans.append(p)
            continue

        # Look up net weight using lowercase token
        k = p.lower()
        w = net_weights.get(k, 0)
        if w != 0:
            # Alpha scales with magnitude of contribution
            alpha = 0.15 + 0.4 * (abs(w) / max_abs)
            if w > 0:
                # Positive: supports REAL
                color = f"rgba(70, 170, 70, {alpha:.2f})"
            else:
                # Negative: supports FAKE
                color = f"rgba(200, 80, 80, {alpha:.2f})"
            spans.append(
                f"<span style='background:{color}; padding:0 3px; "
                f"border-radius:2px;'>{p}</span>"
            )
        else:
            spans.append(p)

    rendered = "".join(spans)

    # HTML template with legend and highlighted article text
    html = f"""
    <html>
      <head>
        <meta charset="utf-8"/>
        <style>
          body {{
            margin: 0;
            padding: 0;
            background: #111;
            font-family: Georgia, serif;
            color: #e0e0e0;
          }}
          .container {{
            width: 820px;
            margin: 2rem auto;
            font-size: 1.05rem;
            line-height: 1.68;
          }}
          h2 {{
            font-weight: 600;
            text-align: left;
            margin-bottom: 1.2rem;
            letter-spacing: 0.3px;
          }}
          .legend {{
            display: flex;
            gap: 1.5rem;
            margin-bottom: 1.2rem;
            font-size: 0.9rem;
            color: #cccccc;
            flex-wrap: wrap;
          }}
          .legend-item {{
            display: inline-flex;
            align-items: center;
            gap: 0.4rem;
          }}
          .color-box {{
            width: 12px;
            height: 12px;
            border-radius: 2px;
            display: inline-block;
          }}
          .color-box.real {{
            background: rgba(70, 170, 70, 0.85);
          }}
          .color-box.fake {{
            background: rgba(200, 80, 80, 0.85);
          }}
          .article {{
            white-space: pre-line;
            text-align: justify;
          }}
        </style>
      </head>
      <body>
        <div class="container">
          <h2>Model Attribution Highlights</h2>
          <div class="legend">
            <div class="legend-item">
              <span class="color-box real"></span>
              <span>Supports REAL (true) prediction</span>
            </div>
            <div class="legend-item">
              <span class="color-box fake"></span>
              <span>Supports FAKE prediction</span>
            </div>
          </div>
          <div class="article">{rendered}</div>
        </div>
      </body>
    </html>
    """
    return html


def explain(model, tokenizer, text, top_k, threshold):
    """
    Run LIME explanation for a given text and model, and aggregate token-level
    contributions into a net weight for highlighting.
    Returns: (label, probabilities, html_highlight, feature_list).
    """
    # Build predict function for LIME
    predict_fn = predict_factory(model, tokenizer)

    # Get model probabilities for the input text
    p = predict_fn([text])[0]
    label_idx = int(np.argmax(p))

    # Run LIME explanation requesting top_k features for both labels
    exp = explainer.explain_instance(
        text, predict_fn, num_features=top_k, labels=[0, 1]
    )

    # Extract explanations per label, robust to missing label explanations
    try:
        fake_items = exp.as_list(label=0)
    except Exception:
        fake_items = []
    try:
        real_items = exp.as_list(label=1)
    except Exception:
        real_items = []

    # Convert to token→weight dictionaries (lowercased token keys)
    fake_dict = {str(k).lower(): v for k, v in fake_items}
    real_dict = {str(k).lower(): v for k, v in real_items}

    # Union of tokens seen in either class explanation
    tokens = set(list(fake_dict.keys()) + list(real_dict.keys()))
    net_weights_all = {}
    features = []

    # Combine fake/real contributions into a net contribution per token
    for t in tokens:
        sf = fake_dict.get(t, 0.0)
        sr = real_dict.get(t, 0.0)
        net = sr - sf  # positive → supports REAL, negative → supports FAKE

        if net > 0:
            direction = "real"
        elif net < 0:
            direction = "fake"
        else:
            direction = "neutral"

        net_weights_all[t] = net

        # Only keep tokens whose net contribution exceeds the threshold
        if abs(net) >= threshold:
            features.append(
                {
                    "token": t,
                    "fake_weight": sf,
                    "real_weight": sr,
                    "net_weight": net,
                    "direction": direction,
                }
            )

    # Apply threshold to net weights used for highlighting (if requested)
    if threshold > 0:
        net_weights = {
            t: w for t, w in net_weights_all.items() if abs(w) >= threshold
        }
    else:
        net_weights = net_weights_all

    # Sort features by absolute net contribution (most important first)
    features.sort(key=lambda x: abs(x["net_weight"]), reverse=True)

    # Map predicted label index back to class name
    label = "real" if label_idx == 1 else "fake"

    # Build highlighted HTML for visual explanation
    html = build_highlighted_html(net_weights, text)
    return label, p.tolist(), html, features


def text_stats(text: str):
    """
    Compute simple text statistics: word, sentence, and paragraph counts.
    """
    words = re.findall(r"\w+", text)
    word_count = len(words)

    # Split on sentence-ending punctuation and drop empty chunks
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    sentence_count = len(sentences)

    # Paragraphs are separated by blank lines
    paragraphs = [p for p in text.split("\n\n") if p.strip()]
    paragraph_count = len(paragraphs)

    return word_count, sentence_count, paragraph_count


# Configure Streamlit page for the fake news detection and interpretation UI
st.set_page_config(page_title="Fake News Detector", layout="wide")

st.title("Fake News Detection: Model Interpretation")

# Sidebar controls for model selection and explanation settings
with st.sidebar:
    st.header("Configuration")
    # Select among multiple model versions
    model_choice = st.selectbox(
        "Model version", ["1.0", "1.1", "1.2", "2.0", "3.0"]
    )
    # Choose input type: URL-based extraction vs manual text
    input_mode = st.radio("Input source", ["URL", "Paste text"])
    # Number of tokens to consider in LIME explanation
    top_k = st.slider("Highlighted tokens (top-k)", 5, 50, 20, 5)
    # Threshold on |net_weight| to filter out low-importance tokens
    threshold = st.slider(
        "Contribution threshold (|net weight|)", 0.0, 1.0, 0.0, 0.01
    )

# Load the selected model and tokenizer (cached)
model, tokenizer = load_selected_model(model_choice)

# Main input area depending on input mode
if input_mode == "URL":
    url = st.text_input("Article URL")
    txt_manual = None
else:
    txt_manual = st.text_area("Article text", height=220)
    url = ""

# Button to trigger the analysis
run = st.button("Analyze", use_container_width=True)

if run:
    try:
        txt = None
        extraction_meta = None

        # Handle URL-based extraction
        if input_mode == "URL":
            if url:
                txt, extraction_meta = fetch_article_text(url)
                if not txt:
                    st.error("Unable to extract text.")
            else:
                st.warning("Enter a URL.")
        # Handle manually pasted text
        else:
            if txt_manual and txt_manual.strip():
                txt = txt_manual.strip()
                paragraphs = [p for p in txt.split("\n\n") if p.strip()]
                extraction_meta = {
                    "paragraphs": len(paragraphs),
                    "title": "",
                    "domain": "",
                    "mode": "manual",
                }

        if txt:
            # Strip leading whitespace from extracted text
            txt = txt.lstrip()

            # Compute basic text statistics
            word_count, sentence_count, paragraph_count = text_stats(txt)

            # Run explanation pipeline: prediction + LIME + HTML + feature table
            label, probs, html, features = explain(
                model, tokenizer, txt, top_k, threshold
            )
            df_features = pd.DataFrame(features)

            # Map internal extraction mode to more human-readable labels
            mode_label_map = {
                "structured": "Structured article body",
                "fallback": "Fallback paragraph scan",
                "manual": "Manual text input",
                "empty": "No content extracted",
                "none": "Not available",
            }
            extraction_mode = ""
            extraction_paragraphs = paragraph_count
            article_title = ""
            article_domain = ""

            if extraction_meta:
                extraction_mode = mode_label_map.get(
                    extraction_meta.get("mode", ""),
                    extraction_meta.get("mode", ""),
                )
                extraction_paragraphs = extraction_meta.get(
                    "paragraphs", paragraph_count
                )
                article_title = extraction_meta.get("title", "")
                article_domain = extraction_meta.get("domain", "")

            # Extract fake/real probabilities from the model output
            fake_prob = float(probs[0])
            real_prob = float(probs[1])

            # Create tabs for different outputs: prediction, highlights, text, features
            tab_output, tab_highlights, tab_text, tab_features = st.tabs(
                [
                    "Model output",
                    "Explanation highlights",
                    "Extracted article text",
                    "Feature-importance table",
                ]
            )

            # TAB: Model output and summary metrics
            with tab_output:
                col1, col2, col3 = st.columns(3)

                # Column 1: prediction summary and model version
                with col1:
                    st.subheader("Prediction")
                    st.markdown(
                        f"""
                        <div style="
                            background:#1c1c1c;
                            padding:0.9rem 1.1rem;
                            border-radius:8px;
                            border:1px solid #333;
                        ">
                        <div style="font-size:0.85rem;color:#aaa;">Model version</div>
                        <div style="font-weight:600;">v{model_choice}</div>
                        <div style="margin-top:0.8rem;font-size:0.85rem;color:#aaa;">Classification</div>
                        <div style="font-size:1.2rem;font-weight:700;text-transform:uppercase;">
                        {label}
                        </div>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

                # Column 2: class probabilities
                with col2:
                    st.subheader("Class probabilities")
                    st.metric("Fake", f"{fake_prob*100:.1f}%")
                    st.metric("Real", f"{real_prob*100:.1f}%")

                # Column 3: text and extraction metrics
                with col3:
                    st.subheader("Article summary")
                    st.markdown(
                        f"""
                        <div style="
                            background:#1c1c1c;
                            padding:0.9rem 1.1rem;
                            border-radius:8px;
                            border:1px solid #333;
                            font-size:0.9rem;
                        ">
                        <div><strong>Words:</strong> {word_count}</div>
                        <div><strong>Sentences:</strong> {sentence_count}</div>
                        <div><strong>Paragraphs (text):</strong> {paragraph_count}</div>
                        <div><strong>Paragraphs (extraction):</strong> {extraction_paragraphs}</div>
                        <div style="margin-top:0.4rem;"><strong>Extraction mode:</strong> {extraction_mode or "Unknown"}</div>
                        <div><strong>Domain:</strong> {article_domain or "N/A"}</div>
                        <div><strong>Title:</strong> {article_title or "N/A"}</div>
                        <div style="margin-top:0.4rem;"><strong>Threshold:</strong> |net weight| ≥ {threshold:.2f}</div>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

            # TAB: HTML explanation (no download options)
            with tab_highlights:
                st.subheader("Highlighted explanation")
                components.html(html, height=900, scrolling=True)

            # TAB: raw extracted article text
            with tab_text:
                st.subheader("Extracted article text")
                st.text_area("Raw text", txt, height=400)
                st.markdown(
                    f"**Words:** {word_count}  |  **Sentences:** {sentence_count}  |  **Paragraphs:** {paragraph_count}"
                )

            # TAB: token-level feature importance table
            with tab_features:
                st.subheader("Token-level feature importance")
                if not df_features.empty:
                    st.dataframe(
                        df_features[
                            [
                                "token",
                                "direction",
                                "fake_weight",
                                "real_weight",
                                "net_weight",
                            ]
                        ],
                        use_container_width=True,
                    )
                else:
                    st.write(
                        "No feature-importance data available for this instance."
                    )

    except Exception as e:
        # Catch and display any error during the analysis pipeline
        st.error(f"{type(e).__name__}: {e}")
